// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoposServer.Data;

#nullable disable

namespace ScoposServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211173659_AddIndexesAndCreatedDate")]
    partial class AddIndexesAndCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoposServer.Domain.Entities.EqEquipment", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("ClassCode")
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("ClassType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ComissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EpbComplexCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EpbDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EpbNextDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EpbNextDatePlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EpbObjectCode")
                        .HasColumnType("text");

                    b.Property<string>("EpbTypeNameCode")
                        .HasColumnType("text");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDel")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ModelCode")
                        .HasColumnType("text");

                    b.Property<string>("MvzCode")
                        .HasColumnType("text");

                    b.Property<string>("MvzName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text");

                    b.Property<string>("ParentName")
                        .HasColumnType("text");

                    b.Property<string>("ParentType")
                        .HasColumnType("text");

                    b.Property<string>("PrDepCode")
                        .HasColumnType("text");

                    b.Property<string>("PrDepName")
                        .HasColumnType("text");

                    b.Property<string>("ProductMonth")
                        .HasColumnType("text");

                    b.Property<string>("ProductYear")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("SystemStat")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UserStat")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("EqEquipment");
                });

            modelBuilder.Entity("ScoposServer.Domain.Entities.EqNotify", b =>
                {
                    b.Property<string>("QmCode")
                        .HasColumnType("text");

                    b.Property<string>("Criticality")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EliminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EliminationStatus")
                        .HasColumnType("text");

                    b.Property<string>("EoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeCodCode")
                        .HasColumnType("text");

                    b.Property<string>("FeCodName")
                        .HasColumnType("text");

                    b.Property<string>("FeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeGrpCode")
                        .HasColumnType("text");

                    b.Property<string>("FeGrpName")
                        .HasColumnType("text");

                    b.Property<string>("FeName")
                        .HasColumnType("text");

                    b.Property<string>("Order")
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("QmCodCode")
                        .HasColumnType("text");

                    b.Property<string>("QmCodName")
                        .HasColumnType("text");

                    b.Property<string>("QmGrpCode")
                        .HasColumnType("text");

                    b.Property<string>("QmGrpName")
                        .HasColumnType("text");

                    b.Property<string>("QmType")
                        .HasColumnType("text");

                    b.Property<string>("RepairStatus")
                        .HasColumnType("text");

                    b.HasKey("QmCode");

                    b.ToTable("EqNotify");
                });
#pragma warning restore 612, 618
        }
    }
}
